config/routes.rb
AnalyticsPortal::Application.routes.draw do

  devise_for :users, :path_prefix => 'd'
  
  resource :account, :only => [:show, :edit, :update]
  resources :users

  resources :dashboard_reports, :only => [:edit, :update]
  resources :dashboards do
    resources :reports do
      member do
        get 'data'
      end
    end
  end
  resources :permissions, :only => [:index]
  resources :roles, :except => [:show]
  resources :reports do
    member do
      get 'data'
    end
  end
  resources :data_sources
  resources :data_segments do
    member do
      get 'start'
    end
  end
  resources :job_runners do # ActiveResource
    member do
      get 'start'
    end
  end
  resources :filter_params
  resources :filter_sets, :except => [:show]

  resource :configuration, :only => [:show, :edit, :update]
  match 'help' => 'help#index'

  root :to => "home#index"

end

app/models/data_segment.rb
class DataSegment < ActiveRecord::Base
  has_many :data_segment_job_runners
  has_many :queries, :dependent => :destroy
  belongs_to :data_source

  validates_presence_of :name, :data_source_id
  validates_uniqueness_of :name
  validates :properties, :json_or_blank => true

  accepts_nested_attributes_for :queries, :allow_destroy => true, :reject_if => lambda { |a| a[:query_string].blank? }

  def job_runners
    @job_runner ||= self.data_segment_job_runners.collect { |d| d.job_runner }
  end

  # TODO implement
  def last_updated
    nil
  end

  # TODO implement
  def next_scheduled
    schedule
  end

  def job_runners_status
    begin
      self.job_runners.collect { |j|
        status = j.status
        "#{status.respond_to?(:message) ? j.status.message : j.status.status}"
      }.join "\n"
    rescue ActiveResource::ServerError, Errno::ECONNREFUSED
      "The data source appears to be down.  Contact your administrator."
    rescue NoMethodError => e
      "#{e.class}: #{e.message}"
    rescue Exception => e
      # TODO log error
      "An unexpected error occurred with the data source.  Contact your administrator.  #{e.class}: #{e.message}"
    end
  end

  def data_source_name
    self.data_source.try(:name)
  end

  def properties_hash
    self.properties.present? ? JSON.parse(self.properties) : {}
  end

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

  def setup_job_runners
    # create data_segment_job_runner and job_runner if they don't already exist
    if self.data_segment_job_runners.blank?
      self.data_segment_job_runners.build
      job_runner = JobRunner.build
      job_runner.database_name = self.data_source.database_name
      job_runner.schedule = self.schedule
      job_runner.save!
      self.data_segment_job_runners.first.job_runner = job_runner
      self.save!
    elsif self.data_segment_job_runners.first.job_runner.blank?
      job_runner = JobRunner.build
      job_runner.database_name = self.data_source.database_name
      job_runner.schedule = self.schedule
      job_runner.save!
      self.data_segment_job_runners.first.job_runner = job_runner
      self.save!
    end

    self.job_runners.each do |jr|
      jr.queries = self.queries.collect do |query|
        begin
          qr = QueryResult.find(query.query_result_id) # nil ID also throws same exception
        rescue ActiveResource::ResourceNotFound
          qr = QueryResult.new
        end
        qr.database_name = self.data_source.database_name
        qr.query_string = query.token_replaced_hive_query_string
        qr.store_in_db = query.store_in_db
        qr.save!
        query.query_result_id = qr.id
        qr.query_result_id = qr.id
        query.save!

        qr # collect
      end
      jr.database_name = self.data_source.database_name
      jr.schedule = self.schedule
      jr.query_results = nil
      jr.status = nil
      jr.save!
    end
  end

  def send_enable_schedule
    self.job_runners.each do |jr|
      jr.enable_schedule
    end
  end

  def send_disable_schedule
    self.job_runners.each do |jr|
      jr.disable_schedule
    end
  end

  def start_job_runners
    setup_job_runners
    self.job_runners.each do |jr|
      jr.start
    end
  end

end

app/controllers/data_segments_controller.rb
class DataSegmentsController < ApplicationController

  load_and_authorize_resource

  include ComboTable
  helper_method :sort_column, :sort_direction
  combo_table :data_segment,
              :columns => [[:name, 'Name'], [:description, 'Description'], [:job_runners_status, 'Status'],
                           [:schedule, 'Schedule']],
              :actions => [:show, :edit, :destroy, :start] ,
              :klass_display_name => 'Job'

  set_tab :analytics
  set_tab :jobs, :sub_nav
  before_filter do
    @sub_nav_group = :analytics
  end

  # # GET /data_segments
  # # GET /data_segments.xml
  # def index
  #   @data_segments = DataSegment.all
  #
  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.xml  { render :xml => @data_segments }
  #   end
  # end

  # GET /data_segments/1
  # GET /data_segments/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @data_segment }
    end
  end

  # GET /data_segments/new
  # GET /data_segments/new.xml
  def new
    @data_segment.data_source = DataSource.first
    @data_segment.queries.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @data_segment }
    end
  end

  # GET /data_segments/1/edit
  def edit
  end

  # POST /data_segments
  # POST /data_segments.xml
  def create
    respond_to do |format|
      if @data_segment.save!
        @data_segment.setup_job_runners
        @data_segment.enable_schedule? ? @data_segment.send_enable_schedule : @data_segment.send_disable_schedule
        format.html { redirect_to(@data_segment, :notice => 'Data segment was successfully created.') }
        format.xml  { render :xml => @data_segment, :status => :created, :location => @data_segment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @data_segment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /data_segments/1
  # PUT /data_segments/1.xml
  def update
    respond_to do |format|
      if @data_segment.update_attributes!(params[:data_segment])
        @data_segment.setup_job_runners
        @data_segment.enable_schedule? ? @data_segment.send_enable_schedule : @data_segment.send_disable_schedule
        format.html { redirect_to(@data_segment, :notice => 'Data segment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @data_segment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /data_segments/1
  # DELETE /data_segments/1.xml
  def destroy
    @data_segment.destroy

    respond_to do |format|
      format.html { redirect_to(data_segments_url) }
      format.xml  { head :ok }
    end
  end

  def start
    @data_segment.start_job_runners

    respond_to do |format|
      format.html { redirect_to(data_segments_url) }
      format.xml  { render :xml => @data_segment }
    end
  end
end

app/helpers/data_segments_helper.rb
module DataSegmentsHelper
end

app/views/data_segments/_form.html.erb
<%= simple_form_for @data_segment do |form| %>

  <div class="dialog-content">
    <%= form.input :name %>
    <%= form.input :description %>
    <%= form.input :schedule, :hint => 'cron format' %>
    <%= form.input :enable_schedule %>

    <% if is_global_admin?(current_user) %>
      <div class='col-4 global-admin'>
        <%= form.association :data_source %>
        <%= form.input :properties %>
        <div id="queries" class="sub-form">
          <h3>Queries</h3>
          <%= form.simple_fields_for :queries do |query| %>
            <%= render 'query_fields', :f => query %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'add query', form, :queries %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <%= render :partial => 'shared/dialog_footer', :locals => {
          :form => form, :cancel_path => data_segments_path} %>
<% end %>

app/views/data_segments/_query_fields.html.erb
<div class="nested-fields">
  <%= f.input :name %>
  <%= f.input :query_string, :input_html => { :rows => 10, :cols => 80 } %>
  <%= f.input :store_in_db, :as => :boolean %>
  <%= f.input :sample_data, :input_html => { :rows => 5, :cols => 80 } %>
  <%= link_to_remove_association "remove query", f %>
</div>

app/views/data_segments/edit.html.erb
<div class="dialog">

  <h1>Edit Job</h1>

  <%= render 'form' %>

  <div class="clear"></div>

</div>

app/views/data_segments/new.html.erb
<div class="dialog">

  <h1>New Job</h1>

  <%= render 'form' %>

  <div class="clear"></div>

</div>

app/views/data_segments/show.html.erb
<div id="content-main">

<p id="notice"><%= notice %></p>

<%= link_to 'Start', start_data_segment_path %>

<p>
  <b>Name:</b>
  <%= @data_segment.name %>
</p>

<p>
  <b>Status:</b>
  <%= @data_segment.job_runners_status %>
</p>

<p>
  <b>Description:</b>
  <%= @data_segment.description %>
</p>

<p>
  <b>Data source:</b>
  <%= @data_segment.data_source_id %>
</p>

<p>
  <b>Schedule:</b>
  <%= @data_segment.schedule %>
</p>

<p>
  <b>Enable Schedule:</b>
  <%= @data_segment.enable_schedule %>
</p>

<p>
  <b>Properties:</b>
  <%= @data_segment.properties %>
</p>

<p>
  <b>Queries:</b>
  <% if @data_segment.queries.present? %>
    <% @data_segment.queries.each do |query| %>
      <table class='queries'>
        <tr><td>query id:</td><td><%= query.id %></td></tr>
        <tr><td>query name:</td><td><%= query.name %></td></tr>
        <tr><td>token replaced query string:</td><td><%= query.token_replaced_hive_query_string %></td></tr>
        <tr><td>sample data:</td><td><%= query.sample_data %></td></tr>
        <tr><td>store in db:</td><td><%= query.store_in_db %></td></tr>
        <tr><td>query result id:</td><td><%= "#{query.query_result_id} (results_#{query.query_result_id})" %></td></tr>
        <tr>
          <td>results<br/> (limit 50):</td>
          <td>
            <table>

              <%- begin %>
                <%- result_set = query.filtered_results(
                        nil, nil, :sql_string => 'SELECT * FROM {table_name} LIMIT 50'
                ).try(:result_set) %>
              <%- rescue %>
                <%- result_set = nil %>
              <% end %>

              <tr>
                <% result_set.try(:column_names).try(:each) do |col| %>
                  <th><%= col.to_s %></th>
                <% end %>
              </tr>

              <% result_set.try(:results).try(:each) do |row| %>
                <tr>
                  <% result_set.try(:column_names).try(:each) do |col| %>
                    <td><%= result_set.value_at(row, col) %></td>
                  <% end %>
                </tr>
              <% end %>

            </table>
          </td>
        </tr>
      </table>
      <br/>
    <% end %>
  <% end %>
</p>

<%= link_to 'Edit', edit_data_segment_path(@data_segment) %> |
<%= link_to 'Back', data_segments_path %>

</div>