config/routes.rb
AnalyticsPortal::Application.routes.draw do

  devise_for :users, :path_prefix => 'd'
  
  resource :account, :only => [:show, :edit, :update]
  resources :users

  resources :dashboard_reports, :only => [:edit, :update]
  resources :dashboards do
    resources :reports do
      member do
        get 'data'
      end
    end
  end
  resources :permissions, :only => [:index]
  resources :roles, :except => [:show]
  resources :reports do
    member do
      get 'data'
    end
  end
  resources :data_sources
  resources :data_segments do
    member do
      get 'start'
    end
  end
  resources :job_runners do # ActiveResource
    member do
      get 'start'
    end
  end
  resources :filter_params
  resources :filter_sets, :except => [:show]

  resource :configuration, :only => [:show, :edit, :update]
  match 'help' => 'help#index'

  root :to => "home#index"

end

app/models/heat_map_report.rb
class HeatMapReport < Report

  def json_data(column_filter_hash, filter_prefs, filter_set)
    filter_prefs = self.filter_prefs if filter_prefs.blank?
    filter_set = self.filter_set if filter_set.blank?

    selected_report_queries = selected_report_queries(filter_prefs)

    if self.table_columns.blank?
      filtered_columns = []
    else
      filtered_columns = self.table_columns.strip.split(%r{,\s*})
    end

    results = []
    selected_report_queries.each do |report_query|
      filtered_result_data = report_query.query.filtered_results(
          filter_prefs, filter_set, :sample_option => self.sample_option, :sql_string => report_query.sql_string
      )
      result_set = filtered_result_data.result_set
      result_set.results_array.each do |row|
        row_array = filtered_columns.collect { |col| result_set.value_at(row, col) }
        results << row_array
      end
    end

    { 'columns' => filtered_columns, 'results' => results }.to_json
  end

end

app/views/heat_map_reports/_display_data.html.erb
<%- # required: report   %>

<div id="map_canvas" style="width:100%; height:100%"></div>

<script type="text/javascript">
    function onSuccess(data,textStatus) {
        $('#ajaxBusy').show();
        _model = SmithMicroHeatMapDataModel.get$();
        _model.init(data);
        __map__.setCenter(_model.map_center);
        __map__.fitBounds(_model.map_bounds);

        var aMarker;
        var aDatum;
        var units = GeolocationDistance.UNITS.feet;
        for (var i = 0; i < _model.length(); i++) {
            aDatum = _model.next_record();
            _add_polygon_overlay(aDatum[GPS_SYMBOL],aDatum[ALPHA_SYMBOL],aDatum);
        }
        $('#ajaxBusy').hide();
    }
    function onError(jqXHR, textStatus, errorThrown) {
        alert("error\n"+textStatus+'\n'+errorThrown);
    }

    var __interval_wait_for_heat_map_utils = -1;

    function wait_for_heat_map_utils() {
        if (__is_loaded_heat_map_utils__) {
            if (__interval_wait_for_heat_map_utils > -1) {
                window.clearInterval(__interval_wait_for_heat_map_utils);
                __interval_wait_for_heat_map_utils = -1;
            }
            $.ajax({
                url: '<%= report_path(@report) %>/data.json',
                dataType: 'json',
                success: onSuccess,
                error: onError
            });
        }
    }

    $(document).ready(function() {
        $('body').append('<div id="ajaxBusy"><p><img src="/heat-maps/ajax-loader.gif"></p></div>');
        $('#ajaxBusy').css({
            display:"none",
            margin:"0px",
            paddingLeft:"0px",
            paddingRight:"0px",
            paddingTop:"0px",
            paddingBottom:"0px",
            position:"fixed",
            right:"50%",
            top:"50%",
            width:"auto"
        });
        $(document).ajaxStart(function(){
            $('#ajaxBusy').show();
        }).ajaxStop(function(){
            $('#ajaxBusy').hide();
        });

        if (__interval_wait_for_heat_map_utils == -1) {
            __interval_wait_for_heat_map_utils = window.setInterval(function() {wait_for_heat_map_utils();}, 250);
        }

    });
</script>

app/views/heat_map_reports/_form.html.erb
<%= simple_form_for @report, :html => {:class => 'dev'} do |form| %>
  <%= form.input :report_type, :as => :hidden %>
  <%= form.input :name %>
  <%= form.input :tag_list, :hint => '(separate by commas)' %>

  <% if is_global_admin?(current_user) %>
    <div class="col-4 global-admin">

      <%= form.input :table_columns, :hint => '(separate by commas)' %>
      <%= form.collection_radio :sample_option, Query::Sample.options, :first, :last %>

      <div id="filter_params" class="sub-form">
        <h3>Filter Params</h3>
        <%= form.simple_fields_for :filter_params do |filter_param| %>
          <%= render 'filter_param_fields', :f => filter_param %>
        <% end %>
        <div class="links">
          <%= link_to_add_association 'create filter param', form, :filter_params %>
        </div>
      </div>

      <div id="filter_prefs" class="sub-form">
        <h3>Filter Prefs</h3>
        <%= form.simple_fields_for :filter_prefs do |filter_prefs| %>
          <%= render 'filter_pref_fields', :f => filter_prefs %>
        <% end %>
        <div class="links">
          <%= link_to_add_association 'create filter pref', form, :filter_prefs %>
        </div>
      </div>

      <div id="report_queries" class="sub-form">
        <h3>Queries</h3>
        <%= form.simple_fields_for :report_queries do |report_query| %>
          <%= render 'report_query_fields', :f => report_query %>
        <% end %>
        <div class="links">
          <%= link_to_add_association 'link query data', form, :report_queries %>
        </div>
      </div>

    </div>
  <% end %>

  <%= form.button :submit %>
<% end %>

app/views/heat_map_reports/new.html.erb
<div id="content-main">

<h1>New Heat Map Report</h1>

<%= render 'heat_map_reports/form' %>

<%= link_to 'Back', reports_path %>

</div>