config/routes.rb
AnalyticsPortal::Application.routes.draw do

  devise_for :users, :path_prefix => 'd'
  
  resource :account, :only => [:show, :edit, :update]
  resources :users

  resources :dashboard_reports, :only => [:edit, :update]
  resources :dashboards do
    resources :reports do
      member do
        get 'data'
      end
    end
  end
  resources :permissions, :only => [:index]
  resources :roles, :except => [:show]
  resources :reports do
    member do
      get 'data'
    end
  end
  resources :data_sources
  resources :data_segments do
    member do
      get 'start'
    end
  end
  resources :job_runners do # ActiveResource
    member do
      get 'start'
    end
  end
  resources :filter_params
  resources :filter_sets, :except => [:show]

  resource :configuration, :only => [:show, :edit, :update]
  match 'help' => 'help#index'

  root :to => "home#index"

end

app/views/shared/_dialog_footer.html.erb
<%- # required: cancel_path %>
<%- form ||= nil %>
<%- dialog_info ||= nil %>
<%- submit_button_text ||= 'Save' %>
<%- obj ||= nil %>

<div class="footer">
  <% if dialog_info.present? %>
    <div class="dialog-info"><%= dialog_info %></div>
  <% end %>
  <% if obj.present? && !obj.new_record? %>
    <%= link_to 'Delete', obj, :confirm => 'Are you sure?', :method => :delete, :class => 'delete-button' %>
  <% end %>
  <div class="buttons-wrapper">
    <div class="buttons">
      <%= link_to 'Cancel', cancel_path, :class => 'cancel-button' %>
      <% if form.present? %>
        <%= form.button :submit, :value => submit_button_text %>
      <% else %>

      <% end %>
      <div class="clear"></div>
    </div>
  </div>
  <div class="clear"></div>
</div>
<div class="clear"></div>

app/views/shared/_footer.html.erb
<div id="footer">

</div>

app/views/shared/_header.html.erb
<div id="header">

  <a href="<%= default_dashboard_path %>" id="smithmicro-logo-main" title="Smith Micro Analytics"></a>

  <div class="main-nav">
    <% if current_user %>

      <%- tab_classes = [Dashboard, User, Role, Configuration].select { |c| can? :read, c } %>

      <%= tabs_tag :builder => ClickableTabsBuilder, :open_tabs => {:class => 'nav-items'} do |tab| %>
        <% if can? :read, Dashboard %>
          <%= tab.analytics 'Analytics', default_dashboard_path, :class => last_tab_class(Dashboard, tab_classes) %>
        <% end %>
        <% if can? :read, User %>
          <%= tab.users 'Users', users_path, :class => last_tab_class(User, tab_classes) %>
        <% end %>
        <% if can? :read, Role %>
          <%= tab.roles 'Roles', roles_path, :class => last_tab_class(Role, tab_classes) %>
        <% end %>
        <% if can? :read, Configuration %>
          <%= tab.configuration 'Config', configuration_path, :class => last_tab_class(Configuration, tab_classes) %>
        <% end %>
      <% end %>

    <% end %>
  </div>

  <% if current_user %>
    <ul class="root-nav">
      <li class="customer-name"><%= Configuration.instance.name %></li>
      <li class="logged-in">Logged in as:
        <br/> <%= link_to "#{current_user.first_name} #{current_user.last_name}", account_path %>
      </li> |
      <li><%= link_to "Log Out", destroy_user_session_path %></li> |
      <li><%= link_to "Help", contextual_help_path, :target => '_blank' %></li>
    </ul>
  <% end %>
  <div class="clear"></div>

  <% if current_user %>
    <%= render :partial => 'shared/sub_nav', :locals => {:sub_nav_group => @sub_nav_group} %>
  <% end %>

  <% if notice.present? %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alert"><%= alert %></p>
  <% end %>
  <% if !current_user && notice.blank? && alert.blank? %>
    <p class="no-message">&nbsp;</p>
  <% end %>

</div>

app/views/shared/_search.html.erb
<%-# objects_sym required %>
<%- objects_string = objects_sym.to_s %>

<%= form_tag url_for(objects_sym), :method => 'get', :id => "#{objects_string}_search", :class => 'search-form' do %>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>

  <span class="search-left-bg"></span>
  <span class="search-icon"></span>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Go", :name => nil, :class => 'submit-button' %>
  <%= link_to '', {:controller => objects_string, :direction => params[:direction], :sort => params[:sort] },
              { :class => 'clear-button', :title => 'Clear' } %>
<% end %>

app/views/shared/_sub_nav.html.erb
<%- sub_nav_group ||= nil %>

<div class="sub-nav">
  <%= tabs_tag :builder => ClickableTabsBuilder, :namespace => :sub_nav, :open_tabs => {:class => 'nav-items'} do |tab| %>

    <% if sub_nav_group == :analytics %>

      <% if can? :read, Dashboard %>
        <%= tab.dashboard 'Dashboard', default_dashboard_path %>
      <% end %>
      <%= tab.reports 'Reports', reports_path %>
      <% if can? :read, FilterSet %>
        <%= tab.data_segments 'Data Segments', filter_sets_path %>
      <% end %>
      <% if can? :read, DataSegment %>
        <%= tab.jobs 'Jobs', data_segments_path %>
      <% end %>
      <% if can? :read, DataSource %>
        <%= tab.data_sources 'Data Sources', data_sources_path, :class => 'global-admin' %>
      <% end %>
      <% if can? :read, FilterParam %>
        <%= tab.filter_params 'Filter Params', filter_params_path, :class => 'global-admin' %>
      <% end %>

    <% elsif sub_nav_group == :users %>

      <% if can? :read, User %>
        <%= tab.users 'Users', users_path %>
      <% end %>

    <% elsif sub_nav_group == :account %>

      <%= tab.account 'My Account', account_path %>

    <% elsif sub_nav_group == :roles %>

      <% if can? :read, Role %>
        <%= tab.roles 'Roles', roles_path %>
      <% end %>

    <% elsif sub_nav_group == :configuration %>

      <% if can? :read, Configuration %>
        <%= tab.configuration 'Configuration', configuration_path %>
      <% end %>

    <% elsif sub_nav_group == :help %>

      <%= tab.help 'Help', help_path %>

    <% else %>
      <!-- -->
    <% end %>
  <% end %>
</div>
<div class="clear"></div>

app/views/shared/_sub_nav_2.html.erb
<%- objects ||= [] %>
<%- object ||= nil %>
<%- object_sym ||= nil %>
<%- object_klass ||= (object_sym.present? ? object_sym.to_s.camelize.constantize : nil) %>
<%- objects_sym ||= object_sym.to_s.pluralize %>
<%- klass_display_name ||= object_sym.to_s.humanize.titleize %>
<%- hide_search ||= false %>
<%- hide_action ||= false %>
<%- search_on_left ||= false %>
<%- show_title ||= false %>
<%- action ||= 'new' %>

<div class="sub-nav-2 <%= search_on_left ? 'search-left' : '' %>">

  <% if objects.present? || !hide_action %>
    <%= tabs_tag :builder => ActionTabsBuilder, :namespace => :sub_nav_2,
                 :open_tabs => { :class => 'nav-items' } do |tab| %>

      <% if object.present? && objects.present? %>
        <% objects.each do |current_object| %>
          <%= tab.send("#{object_sym.to_s}_#{current_object.id}".to_sym, current_object.name,
                       polymorphic_path(current_object), edit_polymorphic_path(current_object)) %>
        <% end %>
      <% end %>

      <% if !hide_action && (can? action.to_sym, object_klass) %>
        <%= tab.send("#{action}_#{object_sym.to_s}".to_sym, "#{action.capitalize} #{klass_display_name}",
                     send("#{action}_polymorphic_path", object_sym), nil, :class => "action-tab") %>
      <% end %>

    <% end %>
  <% end %>

  <% if !hide_search %>
    <%= render :partial => 'shared/search', :locals => { :objects_sym => objects_sym } %>
  <% end %>

  <% if show_title && object.present? %>
    <div class="title">
      <span class="name">
        <%= object.name %><%= link_to "&nbsp;".html_safe, edit_polymorphic_path(object), :class => "edit-button" %>
      </span>
      <span class="name">
        <a class="print-button" href="printPage" onclick="smap.initPrintButton(); return false;"></a>
      </span>
    </div>
  <% end %>

</div>
<div class="clear"></div>

app/views/shared/authorization_error.html.erb
<div id="content-main">
</div>