config/routes.rb
AnalyticsPortal::Application.routes.draw do

  devise_for :users, :path_prefix => 'd'
  
  resource :account, :only => [:show, :edit, :update]
  resources :users

  resources :dashboard_reports, :only => [:edit, :update]
  resources :dashboards do
    resources :reports do
      member do
        get 'data'
      end
    end
  end
  resources :permissions, :only => [:index]
  resources :roles, :except => [:show]
  resources :reports do
    member do
      get 'data'
    end
  end
  resources :data_sources
  resources :data_segments do
    member do
      get 'start'
    end
  end
  resources :job_runners do # ActiveResource
    member do
      get 'start'
    end
  end
  resources :filter_params
  resources :filter_sets, :except => [:show]

  resource :configuration, :only => [:show, :edit, :update]
  match 'help' => 'help#index'

  root :to => "home#index"

end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :dashboard_reports, :dependent => :destroy
  has_many :report_queries, :dependent => :destroy
  has_many :dashboards, :through => :dashboard_reports
  has_many :queries, :through => :report_queries
  has_many :filter_param_associations, :as => :optionable, :dependent => :destroy
  has_many :filter_params, :through => :filter_param_associations
  has_many :filter_prefs, :as => :optionable, :dependent => :destroy
  has_many :report_links, :dependent => :destroy
  belongs_to :filter_set

  accepts_nested_attributes_for :report_queries, :allow_destroy => true
  accepts_nested_attributes_for :filter_param_associations, :allow_destroy => true
  accepts_nested_attributes_for :filter_params, :allow_destroy => true
  accepts_nested_attributes_for :filter_prefs, :allow_destroy => true
  accepts_nested_attributes_for :report_links, :allow_destroy => true

  attr_accessor :series_data, :report_type

  # TODO define
  #attr_accessible :filter_set_id ...

  acts_as_taggable

  validates :name, :presence => true
  validates :filter_set_id, :presence => true

  # for single table inheritance controller
  def self.inherited(child)
    child.instance_eval do
      def model_name
        Report.model_name
      end
    end
    super
  end

  # for single table inheritance controller
  def self.report_subclasses
    descendants
  end

  # for single table inheritance controller
  def self.report_subclasses_strings
    report_subclasses.collect { |c| c.to_s }.sort
  end

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

private ###############################

  def selected_report_queries(filter_prefs)
    filter_param_with_groups = self.filter_params.select { |fp| fp.filter_param_type == 'query_select' }
    query_filter_groups = filter_param_with_groups.collect { |fp| JSON.parse(fp.column) }.flatten.uniq
    valid_report_queries = self.report_queries.select do |report_query|
      if report_query.query.blank?
        false
      elsif query_filter_groups.include?(report_query.query_select_group)
        # need to see what groups are enabled
        enabled_filters = filter_prefs.select { |pref| pref.selected.present? }
        enabled_groups = enabled_filters.collect { |pref| pref.selected }
        # in Ruby 1.8 this is an array, in Ruby 1.9 it's a hash
        enabled_groups.blank? || enabled_groups.include?(report_query.query_select_group)
      else
        true
      end
    end
    valid_report_queries
  end

  # params can be either :filter_param or :report_query
  def series_data_array(data, params = {})
    if data.blank?
      return []
    end

    params ||= {}
    filter_param = params[:filter_param]
    report_query = params[:report_query]
    if filter_param.present?
      x_col = filter_param.date_column
      y_col = filter_param.column
      name_col = nil
      radius_col = nil
    elsif report_query.present?
      x_col = report_query.x_column
      y_col = report_query.y_column
      name_col = report_query.name_column
      radius_col = report_query.radius_column
    else
      raise ':filter_param or :report_query required'
    end

    columns = data.result_set.column_names_array
#    raise 'columns must not be blank' if columns.blank?
    logger.error '[ERROR] columns must not be blank' if columns.blank?

    # construct the series data for highcharts
    result_set = data.result_set
    if radius_col.present? && x_col.present? && y_col.present?
      series_data = result_set.results_array.collect { |row|
        {
            :x => self.class.check_and_convert_to_utc_ms(x_col, result_set.value_at(row, x_col)),
            :y => self.class.check_and_convert_to_utc_ms(y_col, result_set.value_at(row, y_col)),
            :marker => {:radius => result_set.value_at(row, radius_col)},
            :name => result_set.value_at(row, name_col)
        }
      }
    elsif x_col.blank? && y_col.present?
      series_data = result_set.results_array.collect { |row|
        self.class.check_and_convert_to_utc_ms(y_col, result_set.value_at(row, y_col))
      }
    elsif x_col.present? && y_col.present?
      series_data = result_set.results_array.collect { |row|
        [
            self.class.check_and_convert_to_utc_ms(x_col, result_set.value_at(row, x_col)),
            self.class.check_and_convert_to_utc_ms(y_col, result_set.value_at(row, y_col))
        ]
      }
    else
      raise "incorrect series data columns specified: #{x_col}, #{y_col}, #{radius_col}, #{radius_col}"
    end
    return series_data
  end

  def self.check_and_convert_to_utc_ms(date_col, val)
    if val.is_a?(Time)
      val.to_i * 1000
    elsif (date_col.eql? "date_by_day") || (date_col.eql? "c_date")
      DateTime.strptime(val, '%Y-%m-%d').to_i * 1000
    elsif (date_col.eql? "date_by_month") || (date_col.eql? "server_date")
      DateTime.strptime(val, '%Y-%m').to_i * 1000
    elsif date_col.eql? "date_by_hour"
      DateTime.strptime(val, '%Y-%m-%d %H').to_i * 1000
    elsif date_col.eql? "hour"
      val.to_i * 3600000
    else
      # TODO improve type preservation as this is a hack
      begin
        Integer(val)
      rescue
        begin
          Float(val)
        rescue
          val
        end
      end
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  load_and_authorize_resource

  set_tab :analytics
  set_tab :reports, :sub_nav
  before_filter do
    @sub_nav_group = :analytics
  end

  # GET /reports
  # GET /reports.xml
  def index
    respond_to do |format|
      format.html { render :layout => 'two_col' } # index.html.erb
      format.xml  { render :xml => @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.xml
  def show
    @reports = Report.accessible_by(current_ability).search(params[:search])
    @displayed_reports = [@report]

    respond_to do |format|
      format.html { render :layout => 'two_col' }
      format.xml  { render :xml => @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.xml
  def new
    render_new_subclass = false
    @report_type = params[:report_type]
    if Report.report_subclasses_strings.include? @report_type
      @report = @report_type.constantize.new
      @report.report_type = @report_type
      render_new_subclass = true
    else
      @report = Report.new
    end

    respond_to do |format|
      if render_new_subclass
        format.html { render_report @report, :template => 'new' }
        format.xml  { render :xml => @report }
      else
        format.html # new.html.erb
        format.xml  { render :xml => @report }
      end
    end
  end

  # GET /reports/1/edit
  def edit
    @report.filter_param_associations.each do |filter_param_association|
      if filter_param_association.filter_prefs.blank?
        @report.filter_prefs.build(:filter_param_association_id => filter_param_association.id)
      end
    end
  end

  # POST /reports
  # POST /reports.xml
  def create
    @report_type = params[:report][:report_type] if params[:report]
    if Report.report_subclasses_strings.include? @report_type
      @report = Report.new(params[:report])
      @report = @report_type.constantize.new(params[:report])
      @report.report_type = @report_type
    else
      @report = Report.new(params[:report])
    end

    respond_to do |format|
      if @report.save
        format.html { redirect_to(@report, :notice => 'Report was successfully created.') }
        format.xml  { render :xml => @report, :status => :created, :location => @report }
      else
        format.html { render_report @report, :template => "new" }
        format.xml  { render :xml => @report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.xml
  def update
    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to(@report, :notice => 'Report was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.xml
  def destroy
    @report.destroy

    respond_to do |format|
      format.html { redirect_to(reports_url) }
      format.xml  { head :ok }
    end
  end

  def data
    @report = Report.find(params[:id])

    dashboard = (params[:dashboard_id].present? ? Dashboard.find(params[:dashboard_id]) : nil)
    if dashboard
      dashboard_report = DashboardReport.where(:report_id => @report.id, :dashboard_id => dashboard.id).first
      filter_prefs = dashboard_report.filter_prefs
      filter_set = dashboard.filter_set
    else
      filter_prefs = nil
      filter_set = nil
    end
    respond_to do |format|
      format.json { render :json => @report.json_data({}, filter_prefs, filter_set) }
    end
  end

end

app/helpers/reports_helper.rb
module ReportsHelper

  def new_chart_report_path
    url_for :controller => 'reports', :action => 'new', :report_type => ChartReport.to_s
  end

  def new_table_report_path
    url_for :controller => 'reports', :action => 'new', :report_type => TableReport.to_s
  end

  def new_heat_map_report_path
    url_for :controller => 'reports', :action => 'new', :report_type => HeatMapReport.to_s
  end

  def new_kpi_report_path
    url_for :controller => 'reports', :action => 'new', :report_type => KpiReport.to_s
  end

end

app/views/reports/_content_banner.html.erb
<%= render :partial => 'shared/sub_nav_2', :locals => {
        :object_sym => :report, :search_on_left => true, :hide_action => true, :show_title => true,
        :object => @report
} %>

app/views/reports/_debug_info.html.erb
<div class="debug">
  <b>Queries</b>
  <ul>
    <% @report.report_queries.each do |report_query| %>
      <%- q = report_query.query %>
      <li><%= link_to "#{q.name} - (rq-#{report_query.id})", 'http://analytics-admin:3001' + QueryResult.element_path(
              (q.query_result_id || q.id), :sample_option => @report.sample_option,
              :sql_string => report_query.sql_string)
      %></li>
    <% end %>
  </ul>
</div>

app/views/reports/_display_data.html.erb
<div id="report_<%= report.id %>_content" class= "report-content">
  report type undefined
</div>

app/views/reports/_filter_param_fields.html.erb
<%= render :partial => 'filter_params/filter_param_fields', :locals => { :f => f, :report => @report } %>

app/views/reports/_filter_pref_fields.html.erb
<div class="nested-fields">
  <%= f.association :filter_param, :as => :select, :collection => @report.filter_params %>
  <%= f.input :values %>
  <%= link_to_remove_association "remove filter pref", f %>
</div>

app/views/reports/_report_link_fields.html.erb
<div class="nested-fields">
  <%= f.input :name %>
  <%= f.input :filter_columns, :hint => 'comma separated, optional' %>
  <%= f.association :linked_report, :as => :select, :collection => Report.all %>

  <%= link_to_remove_association "remove report link", f %>
</div>

app/views/reports/_report_query_fields.html.erb
<div class="nested-fields">
  <%= f.association :query, :as => :select, :collection => Query.stored_in_db %>
  <%- # TODO use polymorphism for this check... unfortunately the cocoon gem doesn't play nice %>
  <% if @report.instance_of?(ChartReport) %>
    <%= f.input :chart_type, :as => :select, :collection => ChartReport::ChartType.options, :include_blank => true %>
    <%= f.input :chart_params, :input_html => { :rows => 5, :cols => 80 } %>
    <%= f.input :y_axis, :hint => 'required', :input_html => { :size => 25 } %>
    <%= f.input :y_column, :hint => 'required' %>
    <%= f.input :x_column, :hint => 'optional' %>
    <%= f.input :name_column, :hint => 'optional' %>
    <%= f.input :radius_column, :hint => 'optional' %>
  <% end %>
  <%= f.input :query_select_group, :hint => 'optional' %>
  <%= f.input :sql_string, :hint => 'optional', :input_html => { :rows => 10, :cols => 80 } %>
  <%= link_to_remove_association "unlink query data", f %>
</div>

app/views/reports/_reports_js.html.erb
<%- dashboard ||= nil %>

<% if @displayed_reports.present? %>
    <% @displayed_reports.each do |report| %>
        <% if report.instance_of? HeatMapReport %>
            <style type="text/css">
                #map_canvas { height: 100% }
            </style>
            <script language="Javascript" type="text/javascript">
                var __map__;
                var _model = {};

                var const_function_symbol = 'function';

                var const_object_symbol = 'object';
                var const_string_symbol = 'string';

                var __infowindow__;

                var __defaultLatLng__;

                var __is_loaded_heat_map_utils__ = false;

                var __callback_heat_map_utils__ = function () {
                    __is_loaded_heat_map_utils__ = true;
                };

                function loadScripts() {
                    var script2 = document.createElement("script");
                    script2.type = "text/javascript";
                    script2.src = "/javascripts/heat-map-utils.js";
                    document.body.appendChild(script2);
                }

                function initialize() {
                    loadScripts();
                    var __defaultLatLng__ = new google.maps.LatLng(37.331789, -122.029620);
                    var myOptions = {
                        zoom: 8,
                        maxZoom: 15,
                        minZoom: 8,
                        streetViewControl: false,
                        center: __defaultLatLng__,
                        mapTypeId: google.maps.MapTypeId.ROADMAP
                    }
                    var ele = $("#content-body > div:first");
                    var h = ele.height();
                    if (h == 0) {
                        h = ele.css('height');
                    }
                    var w = ele.width();
                    $('#map_canvas').css('width',w).css('height',400);
                    __map__ = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
                }

                $(window).load(function () {
                    var script1 = document.createElement("script");
                    script1.type = "text/javascript";
                    script1.src = "http://maps.google.com/maps/api/js?v=3.4&libraries=geometry&sensor=false&callback=initialize";
                    document.body.appendChild(script1);
                });
            </script>
        <% end %>
    <% end %>
<% end %>

<script type="text/javascript">
    $(document).ready(function() {
        <% if @displayed_reports.present? %>
            <% @displayed_reports.each do |report| %>

            <% if report.instance_of? ChartReport %>
                <%- # funny syntax below as a single statement is due to a rubymine bug %>
                smap.initChartReport(<%= "#{dashboard.nil? ? 'null' : dashboard.id},
                    #{report.id}, #{report.highcharts_params_to_render.to_json},
                    #{report.tooltip_formatter}".html_safe %>);
                <% elsif report.instance_of? TableReport %>
                    smap.initTableReport(<%= "#{dashboard.nil? ? 'null' : dashboard.id}, #{report.id}" %>);
                <% elsif report.instance_of? KpiReport %>
                    smap.initKpiReport(<%= "#{dashboard.nil? ? 'null' : dashboard.id}, #{report.id}" %>);
                <% elsif report.instance_of? HeatMapReport %>
                    // +++
                <% end %>

            <% end %>
        <% end %>
    });
</script>

app/views/reports/_reports_nav.html.erb
<div class="spacer">
  <% if is_global_admin?(current_user) %>
    <%= link_to "new report", new_report_path %>
  <% end %>
</div>

<ul id="tree">
  <% Report.tag_counts.each do |tag| %>
    <li id="tag_<%= tag.id %>">
      <span class="folder"><%= tag.name %></span>

      <ul>
        <% Report.tagged_with(tag).order('name ASC').each do |report| %>
          <li class="file<%= @displayed_reports.try(:include?, report) ? ' active-file' : '' %>">
            <%= link_to report.name, report %>
            <% if @displayed_reports.try(:include?, report) %>
              <span>&gt;</span>
            <% end %>
          </li>
        <% end %>
      </ul>

    </li>
  <% end %>
</ul>

<script type="text/javascript">
  $(document).ready(function() {
    smap.initTree();
  });
</script>

app/views/reports/edit.html.erb
<div class="dialog">

  <h1>Edit Report</h1>

  <%= render_report @report, :partial => 'form' %>
  <div class="clear"></div>
</div>

app/views/reports/index.html.erb
<div id="content-main">

  <%= render :partial => 'content_banner' %>
  <div id="sidebar">
    <%= render :partial => 'reports_nav' %>
  </div>

  <div class="clear"></div>
</div>

app/views/reports/new.html.erb
<div class="dialog">
  <h1>Select a Report Type</h1>

  <div class="dialog-content">
    <div class="col-a">
    <%= link_to 'New Chart Report', new_chart_report_path %>
    <br/>
    <%= link_to 'New Table Report', new_table_report_path %>
    <br/>
    <%= link_to 'New Heat Map Report', new_heat_map_report_path %>
    <br/>
    <%= link_to 'New KPI Report', new_kpi_report_path %>
    <br/>
    </div>

    <%= render :partial => 'shared/dialog_footer', :locals => {
            :form => nil, :cancel_path => reports_path } %>

  </div>
  <div class="clear"></div>

</div>

app/views/reports/show.html.erb
<div id="content-main">

  <%= render :partial => 'content_banner' %>
  <div id="sidebar">
    <%= render :partial => 'reports_nav' %>
  </div>

  <div id="content-wrapper">
    <div id="content-body" class="full-report">
      <div id="report_<%= @report.id %>">
        <%= render_report @report, :partial => 'display_data', :locals => {:report => @report} %>
      </div>

      <% if is_global_admin?(current_user) %>
        <%= render :partial => 'debug_info' %>
      <% end %>
    </div>
  </div>

  <div class="clear"></div>
</div>